services:
  - type: worker
    name: shelldon-bot
    runtime: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    autoDeploy: true
    envVars:
      - key: TOKEN
        sync: false
      - key: CLIENT_ID
        sync: false
      - key: GUILD_ID
        sync: false
      - key: ANNOUNCE_CHANNEL_ID
        sync: false
      - key: ALLOWED_ROLE_ID
        sync: false
